CREATE EXTENSION IF NOT EXISTS "pgcrypto";

DROP TABLE IF EXISTS payroll CASCADE;
DROP TABLE IF EXISTS leaves CASCADE;
DROP TABLE IF EXISTS attendance CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS positions CASCADE;
DROP TABLE IF EXISTS departments CASCADE;

CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'Active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE positions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  level TEXT DEFAULT 'Mid',
  status TEXT NOT NULL DEFAULT 'Open',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  position_id BIGINT REFERENCES positions(id) ON DELETE SET NULL,
  salary NUMERIC(12,2) DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Active',
  hire_date DATE DEFAULT CURRENT_DATE,
  profile_pic TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  check_in TIME,
  check_out TIME,
  status TEXT NOT NULL DEFAULT 'Present',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(employee_id, date)
);

CREATE TABLE leaves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  leave_type TEXT NOT NULL DEFAULT 'Annual',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending',
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (end_date >= start_date)
);

CREATE TABLE payroll (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  pay_period TEXT NOT NULL,
  basic_salary NUMERIC(12,2) NOT NULL DEFAULT 0,
  bonus NUMERIC(12,2) NOT NULL DEFAULT 0,
  deductions NUMERIC(12,2) NOT NULL DEFAULT 0,
  net_pay NUMERIC(12,2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'Draft',
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(employee_id, pay_period)
);

CREATE INDEX idx_positions_department_id ON positions(department_id);
CREATE INDEX idx_employees_department_id ON employees(department_id);
CREATE INDEX idx_employees_position_id ON employees(position_id);
CREATE INDEX idx_attendance_employee_id ON attendance(employee_id);
CREATE INDEX idx_attendance_date ON attendance(date);
CREATE INDEX idx_leaves_employee_id ON leaves(employee_id);
CREATE INDEX idx_payroll_employee_id ON payroll(employee_id);

INSERT INTO departments (name, description, status) VALUES
('Engineering', 'Builds and maintains JavaGoat products.', 'Active'),
('People Operations', 'HR, hiring and employee experience.', 'Active'),
('Finance', 'Payroll, budgeting and reporting.', 'Active'),
('Sales', 'Revenue and customer growth.', 'Active');

INSERT INTO positions (title, description, department_id, level, status) VALUES
('Full-Stack Python Developer', 'Owns Flask, APIs and frontend integrations.', 1, 'Senior', 'Open'),
('HR Generalist', 'Supports employee lifecycle operations.', 2, 'Mid', 'Open'),
('Payroll Specialist', 'Runs payroll and compensation operations.', 3, 'Mid', 'Open'),
('Account Executive', 'Manages customer acquisition.', 4, 'Mid', 'Open');

INSERT INTO employees
(name, email, phone, department_id, position_id, salary, status, hire_date, profile_pic)
VALUES
('Ava Stone', 'ava@javagoat.hr', '+1-555-0101', 1, 1, 98000, 'Active', CURRENT_DATE - INTERVAL '120 days', 'https://api.dicebear.com/7.x/initials/svg?seed=Ava%20Stone&backgroundColor=6D28D9&textColor=ffffff'),
('Noah Kim', 'noah@javagoat.hr', '+1-555-0102', 2, 2, 72000, 'Active', CURRENT_DATE - INTERVAL '80 days', 'https://api.dicebear.com/7.x/initials/svg?seed=Noah%20Kim&backgroundColor=0EA5E9&textColor=ffffff'),
('Mia Patel', 'mia@javagoat.hr', '+1-555-0103', 3, 3, 76000, 'On Leave', CURRENT_DATE - INTERVAL '45 days', 'https://api.dicebear.com/7.x/initials/svg?seed=Mia%20Patel&backgroundColor=10B981&textColor=ffffff'),
('Leo Rivera', 'leo@javagoat.hr', '+1-555-0104', 4, 4, 83000, 'Active', CURRENT_DATE - INTERVAL '20 days', 'https://api.dicebear.com/7.x/initials/svg?seed=Leo%20Rivera&backgroundColor=F97316&textColor=ffffff');

INSERT INTO attendance (employee_id, date, check_in, check_out, status, notes) VALUES
(1, CURRENT_DATE, '09:00', '17:30', 'Present', 'On time'),
(2, CURRENT_DATE, '09:20', '17:20', 'Late', 'Traffic delay'),
(3, CURRENT_DATE, NULL, NULL, 'Absent', 'Approved leave'),
(4, CURRENT_DATE, '08:55', '17:40', 'Present', 'On time'),
(1, CURRENT_DATE - INTERVAL '1 day', '09:05', '17:35', 'Present', NULL),
(2, CURRENT_DATE - INTERVAL '1 day', '09:00', '17:00', 'Remote', NULL),
(4, CURRENT_DATE - INTERVAL '1 day', '09:15', '17:20', 'Late', NULL);

INSERT INTO leaves (employee_id, leave_type, start_date, end_date, status, reason) VALUES
(3, 'Annual', CURRENT_DATE, CURRENT_DATE + INTERVAL '4 days', 'Approved', 'Family trip'),
(2, 'Sick', CURRENT_DATE + INTERVAL '7 days', CURRENT_DATE + INTERVAL '8 days', 'Pending', 'Medical appointment');

INSERT INTO payroll
(employee_id, pay_period, basic_salary, bonus, deductions, net_pay, status, notes)
VALUES
(1, TO_CHAR(CURRENT_DATE, 'YYYY-MM'), 98000 / 12, 500, 120, (98000 / 12) + 500 - 120, 'Generated', 'Monthly payroll'),
(2, TO_CHAR(CURRENT_DATE, 'YYYY-MM'), 72000 / 12, 250, 80, (72000 / 12) + 250 - 80, 'Generated', 'Monthly payroll');
